### ISSUE TITLE
Please create a compiled version ( usually in the /dist/ folder )

### ISSUE THREAD

**Issue by artknight** [selfrefactor/string-fn#1]
Please create a compiled version ( usually in the /dist/ folder )

**Comment by selfrefactor** [comment]
I don't mind doing that, but please specify what you mean by compiled. If you are looking for UMD version, then use ./webVersion.js as stated in the installation instructions.

**Comment by artknight** [comment]
Yeah, i guess i was referring to a standalone JS file, assuming that the webVersion.js is just that. Would you please un-minify it.

**Comment by selfrefactor** [comment]
The unminified file is ./source.js
This file is minified to index.js(for NPM use) and bundle and minified to webVersion.js(for UMD)

I fail to see the usefulness of having one more file with unminified webVersion.js

Still, I am open to change my mind if you provide further info why such file is needed.

**Comment by artknight** [comment]
the problem is that in source.js you are requiring _rambda_ so I would have to load all those dependencies to compile. I just want to grab the final JS file without even compiling it.. if that makes sense

**Comment by selfrefactor** [comment]
Where are you going to use it? Server-side or browser-side?

If it is browser-side, then please check this fiddle [https://jsfiddle.net/Lbse79yz/](https://jsfiddle.net/Lbse79yz/)

There you can see that stringFn is available to use by requiring https://unpkg.com/string-fn@0.2.2/webVersion.js 

In this file, rambda is already included, so you don't need to require it.

**Comment by artknight** [comment]
right, that's why i asked for an un-minified version of the file. :-)

**Comment by selfrefactor** [comment]
So we are good, right?
Can I close the issue now?

**Comment by artknight** [comment]
It was not an issue to begin with. I just wanted an un-minified version of the webVersion.js. Can you provide that?

**Comment by selfrefactor** [comment]
I still fail to see what good that makes. This is final bundled code that and it should be minified. Still, I created gist for you with the unminified version  https://gist.github.com/selfrefactor/709255a9ec8c5eec69ec6d187009f606 and I close the issue

**Comment by artknight** [comment]
Thank you!!!
